export const journeyData = [
  {
    type: 'work',
    title: 'Model Validation Intern (Model Risk Management)',
    company: 'Commerzbank AG',
    location: 'Frankfurt, Germany',
    date: 'Oct 2025 – Mar 2026',
    description: 'Built an automated Python tool screening 4,000+ IT records to flag quantitative models across 12 financial risk domains using a three-tier fuzzy matching engine. Validated IPV processes and applied SABR-based volatility calibration for Market Risk Control.',
  },
  {
    type: 'education',
    title: "Master's in Quantitative Finance",
    company: 'Christian-Albrechts-Universität zu Kiel',
    location: 'Kiel, Germany',
    date: 'Oct 2024 – Sep 2027',
    description: 'Specialising in Computational Finance, Probability Calculus, Inferential Statistics, and advanced time serieseconometrics. Pursuing alongside industry experience in Germany.',
  },
  {
    type: 'work',
    title: 'Data Analyst — Energy Trading (Work Study)',
    company: 'RWE (Rheinisch-Westfälische Elektrizitätswerk)',
    location: 'Essen, Germany',
    date: 'Nov 2024 – Aug 2025',
    description: 'Designed a dual-source automated trading pipeline using OAuth2 and AMQP/RabbitMQ. Built an event-driven Azure Function engine with ML-driven price-spread thresholds and deployed an Azure Data Factory reconciliation pipeline with real-time P&L alerts.',
  },
  {
    type: 'work',
    title: 'Associate Data Scientist Specialist',
    company: 'MetLife US',
    location: 'Hyderabad, India',
    date: 'May 2024 – Sep 2024',
    description: 'Developed a Hybrid RAG pipeline for enterprise audit documents using LangChain, improving semantic recall by 34% and achieving 3× faster document lookup. Implemented BERTopic for topic modelling on eligibility business process data.',
  },
  {
    type: 'work',
    title: 'Analyst Business Consulting',
    company: 'HSBC',
    location: 'Calcutta, India',
    date: 'Oct 2021 – Apr 2024',
    description: 'Developed a corporate/SME credit card PD model (XGBoost + Random Forest) achieving 80%+ recall on a 5% imbalanced dataset. Detected 12 fraudulent customers via fuzzy name matching across 12M records. Converted SAS BAUs to Python on GCP using Apache Airflow, saving 30% processing time.',
  },
  {
    type: 'work',
    title: 'Machine Learning Intern',
    company: 'Ignitus',
    location: 'Remote, USA',
    date: 'Oct 2021 – Apr 2024',
    description: 'Performed EDA on 32 million Instacart customer records and built a multi-page Tableau dashboard to optimise business cost and customer basket prediction.',
  },
  {
    type: 'education',
    title: "Master's in Data Science",
    company: 'University of Kalyani',
    location: 'India',
    date: 'Sep 2019 – Sep 2021',
    description: 'Studied Statistics, Machine Learning, NLP, Deep Learning, and Time Series Forecasting. Foundation for applied AI and quantitative modelling career.',
  },
  {
    type: 'education',
    title: 'Bachelor of Science in Statistics',
    company: 'University of Calcutta',
    location: 'India',
    date: 'Jun 2016 – Jun 2019',
    description: 'Core studies in Applied Statistics, Mathematics, and Economics — building the quantitative foundation for a career in data science and financial modelling.',
  },
];