export const journeyData = [
  {
    type: 'work',
    title: 'Data Scientist',
    company: 'Flix Mobility Tech GmbH',
    location: 'Berlin',
    date: 'Jan 2023 - Present',
    description: 'Enhanced tree-based demand prediction models for bus seat occupancy, improving accuracy through feature engineering and cross-team collaboration.',
  },
  {
    type: 'work',
    title: 'Data Scientist',
    company: 'Pixsy',
    location: 'Berlin',
    date: 'Jun 2021 - Jun 2022',
    description: 'Built an end-to-end ML pipeline for image similarity using Kafka & Spark. Developed a hybrid deep learning model (ResNet/Siamese) that improved matching accuracy by 22%.',
  },
  {
    type: 'education',
    title: 'M.Sc. in Data Science',
    company: 'Otto-von-Guericke Universität',
    location: 'Magdeburg',
    date: '2019 - 2022',
    description: 'Key Courses: Machine Learning, Deep Learning, Learning Generative Models, Computer Vision, Recommenders, Data-Warehouse-Technologies.',
  },
  {
    type: 'work',
    title: 'ML Engineer',
    company: 'Accenture AI',
    location: 'Bengaluru',
    date: 'Nov 2018 - Aug 2019',
    description: 'Developed failure prediction models for trade transactions using Gaussian Mixture Models and optimized critical SQL queries, improving system response time by 38%.',
  },
    {
    type: 'work',
    title: 'Application Analyst',
    company: 'Accenture',
    location: 'Pune, India',
    date: 'Sep 2016 - Nov 2018',
    description: 'Built an email classification and ticket assignment model using Naive Bayes and SVM (F1 score: 0.797). Performed EDA on retail sales data and optimized SQL queries, reducing response time by 38%.',
  },
  {
    type: 'education',
    title: 'B.Tech in Electronics & Communication',
    company: 'GGSIPU',
    location: 'Delhi, India',
    date: '2012 - 2016',
    description: 'Key Subjects: Data Structures and Algorithms, C++, Software Engineering, Applied Mathematics and Statistics.',
  },
];
